name: corebird
version: "1.5.1"
grade: stable
summary: CoreBird Twitter Client
description: |
  Corebird is a modern and lightweight Twitter client for the GNOME 3 desktop. It
  features inline image and video preview, creation of lists and favorites,
  filtering of tweets and full text search. Corebird is able to manage multiple
  Twitter accounts.
icon: corebird.svg
confinement: strict

slots:
  dbus-corebird:
    interface: dbus
    bus: session
    name: org.baedert.corebird

plugs:
  gnome-3-24-platform:
    interface: content
    target: gnome-platform
    default-provider: gnome-3-24:gnome-3-24-platform

apps:
  corebird:
    command: |
      libopenh264-launch desktop-launch
      env GST_PLUGIN_PATH=$SNAP/usr/lib/gstreamer-1.0
          GST_PLUGIN_SYSTEM_PATH=$SNAP/usr/lib/gstreamer-1.0
          GST_PLUGIN_SCANNER=$SNAP/usr/libexec/gstreamer-1.0/gst-plugin-scanner
      $SNAP/usr/bin/corebird

    plugs:
      - gnome-3-24-platform
      - gsettings
      - home
      - network
      - network-observe
      - opengl
      - pulseaudio
      - unity7
      - x11

parts:
  libopenh264-helper:
    source: libopenh264-helper
    source-subdir: libopenh264
    plugin: make
    after: [libopenh264-library]

  libopenh264-library:
    plugin: make
    source: https://github.com/cisco/openh264/archive/v1.7.0.tar.gz
    build-packages:
      - nasm
    stage-packages:
      - bzip2
      - curl
    prime:
      - '-bin/bz*'

  corebird:
    plugin: jhbuild
    module-set: corebird.modules
    module-set-dir: .
    modules:
      - corebird
    cflags: '-Os'
    build-packages:
      - desktop-file-utils
      - doxygen
      - intltool
      - libcairo2-dev
      - libcurl4-openssl-dev
      - libdbus-1-dev
      - libegl1-mesa-dev
      - libenchant-dev
      - libepoxy-dev
      - libfaad-dev
      - libffi-dev
      - libfontconfig1-dev
      - libgl1-mesa-dev
      - libgnutls-dev
      - libgudev-1.0-dev
      - libmount-dev
      - liborc-0.4-dev
      - libproxy-dev
      - libpulse-dev
      - libsqlite3-dev
      - libtiff5-dev
      - libunwind-dev
      - libv4l-dev
      - libwayland-dev
      - libxcb-xkb-dev
      - libxft-dev
      - libxi-dev
      - libxml2-dev
      - libxml2-utils
      - libxslt1-dev
      - libxtst-dev
      - libxv-dev
      - nasm
      - pkg-config
      - ragel
      - tar
      - wget
      - xmlto
      - xutils-dev
      - xz-utils
      - yasm
      - valac
    stage-packages:
      - libcurl3
      - libgnutls30
      - libpulse0
    after: [desktop-gnome-platform, libopenh264-helper]
    prime:
      - bin/*-launch
      - usr/bin/corebird
      - usr/lib/gstreamer-1.0
      - usr/lib/libgspell*
      - usr/lib/libgst*
      #- usr/lib/libjson-glib* # provided by platform
      #- usr/lib/librest* # provided by platform
      #- usr/lib/libsoup* # provided by platform
      - usr/lib/*-linux-gnu/libasn*
      - usr/lib/*-linux-gnu/libasyncns*
      - usr/lib/*-linux-gnu/libboost*
      - usr/lib/*-linux-gnu/libcapnp*
      - usr/lib/*-linux-gnu/libcurl*
      - usr/lib/*-linux-gnu/libdb*
      - usr/lib/*-linux-gnu/libfaad*
      - usr/lib/*-linux-gnu/libFLAC*
      - usr/lib/*-linux-gnu/libheimbase*
      - usr/lib/*-linux-gnu/libheimntlm*
      - usr/lib/*-linux-gnu/libhx509*
      - usr/lib/*-linux-gnu/libkj*
      - usr/lib/*-linux-gnu/libber*
      - usr/lib/*-linux-gnu/libldap*
      - usr/lib/*-linux-gnu/libogg*
      - usr/lib/*-linux-gnu/libprotobuf-lite*
      - usr/lib/*-linux-gnu/libpulse*
      - usr/lib/*-linux-gnu/libroken*
      - usr/lib/*-linux-gnu/librtmp*
      - usr/lib/*-linux-gnu/libsasl*
      - usr/lib/*-linux-gnu/libsndfile*
      - usr/lib/*-linux-gnu/libunwind*
      - usr/lib/*-linux-gnu/libv4l*
      - usr/lib/*-linux-gnu/libwind*
      - usr/libexec/gstreamer-1.0/gst-plugin-scanner
      - usr/local/lib/libopenh264*
      - usr/share/appdata
      - usr/share/dbus-1/services/org.baedert.corebird.service
      - usr/share/glib-2.0/schemas/org.baedert.corebird.gschema.xml
      - usr/share/icons/hicolor/**/corebird.png
      - usr/share/locale/**/corebird.mo

